-- DROP DATABASE NFACE
CREATE DATABASE NFACE
GO
USE NFACE
GO
CREATE TABLE PERSONAL
(
	ID INT PRIMARY KEY,
	TIME_UPDATE DATETIME  NOT NULL,
	IMG_FACE VARCHAR(MAX)   NOT NULL,
	IMG VARCHAR(MAX)  NOT NULL,
	TYPE_PS INT   DEFAULT 0, --0: KHÁCH, 1: NHÂN VIÊN, 2: BLACKLIST
	GHICHU NVARCHAR(MAX),
)

CREATE TABLE EMPLOYEE
(
	ID INT PRIMARY KEY,
	ID_PS INT REFERENCES PERSONAL(ID),
	NAME NVARCHAR(50) NOT NULL,
	GENDER NVARCHAR(3) CHECK (GENDER in ('Nam',N'Nữ')) not null,
	PHONE NVARCHAR(20) NOT NULL,
	BIRTHDAY DATE NOT NULL,
	ADDRESS_EMP NVARCHAR(MAX),
	CMT VARCHAR(12) NOT NULL,
	EMAIL VARCHAR(200),
	IMG_FACE VARCHAR(MAX),
	ISDELETE BIT DEFAULT 0,
	GHICHU NVARCHAR(MAX),
)

CREATE TABLE HISTORY
(
	ID INT PRIMARY KEY,
	ID_PER INT REFERENCES PERSONAL(ID),
	TIME_UPDATE DATETIME NOT NULL,
	IN_OUT BIT DEFAULT 0, --0: VÀO, 1: RA
	IMG_FACE VARCHAR(MAX) NOT NULL,
	IMG VARCHAR(MAX) NOT NULL,
	GHICHU NVARCHAR(MAX),
)

CREATE TABLE ATTENDANCE
(
	ID INT PRIMARY KEY,
	ID_EMP INT REFERENCES EMPLOYEE(ID),
	IMG_IN VARCHAR(MAX),
	IMG_OUT VARCHAR(MAX),
	DATE_ATT DATE NOT NULL,
	TIME_IN TIME,
	TIME_OUT TIME,
	GHICHU NVARCHAR(MAX)
)